modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="valine_energymod"
version="${file.jarVersion}"
displayName="Valine_Energy"
logoFile=""

[[dependencies.valine_energymod]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.valine_energymod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
